services:
    # for use later
    ship_cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments:
            - %kernel.cache_dir%/ship

    app_pdo:
        class: PDO
        arguments:
            - 'mysql:host=localhost;dbname=oop'
            - 'summer'
            - 'camp'
        calls:
            - method: setAttribute
              arguments:
                - "@=constant('PDO::ATTR_ERRMODE')"
                - "@=constant('PDO::ERRMODE_EXCEPTION')"

    ship_loader:
        class: AppBundle\Service\ShipLoader
        arguments: ['@app_pdo']

    cacheable_ship_loader:
        class: AppBundle\Service\CacheableShipLoader
        arguments: ['@ship_loader', '@ship_cache']

    random_ship_selector:
        class: AppBundle\Service\RandomShipSelector
        arguments: ['@ship_loader']

framework:
    secret: %secret%
    templating:
        engines: [twig]
    profiler:
        enabled: %kernel.debug%

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: %monolog_action_level%
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
